"""Stage 5: Generate the model card for each output."""
import json
from pathlib import Path

from blockquant import cards
from blockquant.models import QuantConfig, QuantFormat, QuantOutput
from blockquant.utils.logger import get_logger

logger = get_logger(__name__)


def run(config: QuantConfig, workspace: Path, outputs: list[QuantOutput]) -> None:
    """Write README.md for each output. EXL3 gets the polished template card."""
    exl3_outputs = [o for o in outputs if o.format == QuantFormat.EXL3]
    exl3_ctx = _exl3_context(config, workspace, exl3_outputs) if exl3_outputs else None

    for output in outputs:
        if output.format == QuantFormat.EXL3 and exl3_ctx is not None:
            try:
                card = _render_exl3_card(config, output, exl3_ctx)
            except Exception as exc:  # never fail the run over a card
                logger.warning(f"Polished card failed ({exc}); using stub")
                card = _stub_card(config, output)
            card_path = Path(output.output_path) / "README.md"
        else:
            card = _stub_card(config, output)
            card_path = Path(output.output_path).parent / f"README-{output.variant}.md"

        with open(card_path, "w") as f:
            f.write(card)


def _load_model_config(workspace: Path) -> dict:
    config_path = workspace / "model" / "config.json"
    try:
        return json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _resolve_owner(config: QuantConfig) -> str:
    if config.hf_org:
        return config.hf_org
    token = config.hf_token
    if not token:
        return ""
    try:
        from huggingface_hub import HfApi

        return HfApi(token=token).whoami().get("name", "")
    except Exception:
        return ""


def _exl3_context(config: QuantConfig, workspace: Path, exl3_outputs: list[QuantOutput]) -> dict:
    """Build the shared facts every EXL3 card in this run needs."""
    base_name = config.model_id.split("/")[-1]
    owner = _resolve_owner(config)
    model_config = _load_model_config(workspace)
    cal_rows = config.cal_rows or 250

    quant_rows = []
    repo_ids = []
    for out in exl3_outputs:
        repo_id = cards.exl3_repo_id(owner, base_name, out.variant)
        repo_ids.append(repo_id)
        quant_rows.append({
            "variant": out.variant,
            "head_bits": config.head_bits,
            "cal_rows": cal_rows,
            "size_gb": (out.file_size_mb / 1024.0) if out.file_size_mb else None,
            "url": f"https://huggingface.co/{repo_id}",
        })

    license_id = cards.fetch_license(config.model_id, config.hf_token or None)
    collection_url = f"https://huggingface.co/{owner or 'collections'}"
    if owner and config.hf_token:
        collection_url = cards.ensure_collection(
            owner=owner, base_name=base_name, token=config.hf_token,
        )

    return {
        "owner": owner,
        "base_name": base_name,
        "model_config": model_config,
        "cal_rows": cal_rows,
        "quant_rows": quant_rows,
        "license_id": license_id,
        "collection_url": collection_url,
        "quantized_by": owner or "blockquant",
    }


def _render_exl3_card(config: QuantConfig, output: QuantOutput, ctx: dict) -> str:
    repo_id = cards.exl3_repo_id(ctx["owner"], ctx["base_name"], output.variant)
    return cards.render_exl3_card(
        base_repo=config.model_id,
        repo_id=repo_id,
        variant=output.variant,
        head_bits=config.head_bits,
        cal_rows=ctx["cal_rows"],
        size_gb=(output.file_size_mb / 1024.0) if output.file_size_mb else None,
        model_config=ctx["model_config"],
        quant_rows=ctx["quant_rows"],
        collection_url=ctx["collection_url"],
        license_id=ctx["license_id"],
        quantized_by=ctx["quantized_by"],
    )


def _stub_card(config: QuantConfig, output: QuantOutput) -> str:
    """Minimal card for GGUF, or the EXL3 fallback when the renderer can't run."""
    model_name = config.model_id.split("/")[-1]
    if output.format == QuantFormat.EXL3:
        fmt_tag, fmt_label = "exl3", "EXL3"
    else:
        fmt_tag, fmt_label = "gguf", output.variant.upper() + " GGUF"
    return f"""---
base_model: {config.model_id}
tags:
- {fmt_tag}
- quantized
- blockquant
---

# {model_name} {fmt_label}

Auto-generated by [BlockQuant](https://github.com/Honkware/blockquant).

| Attribute | Value |
|-----------|-------|
| Base model | `{config.model_id}` |
| Variant | {output.variant} |
| File size | {output.file_size_mb:.1f} MB |
"""
