"""Stage 5: Generate quality metrics and model card."""
from pathlib import Path

from blockquant.models import QuantConfig, QuantFormat, QuantOutput
from blockquant.utils.logger import get_logger

logger = get_logger(__name__)


def run(config: QuantConfig, workspace: Path, outputs: list[QuantOutput]) -> None:
    """Generate model card for each output."""
    for output in outputs:
        # Perplexity (lightweight)
        if output.format == QuantFormat.GGUF:
            try:
                from llama_cpp import Llama

                llm = Llama(str(output.output_path), n_ctx=512, verbose=False)
                text = "The quick brown fox jumps over the lazy dog. " * 20
                tokens = llm.tokenize(text.encode())
                # Store token count as rough perplexity proxy
                _ = tokens
            except Exception:
                pass

        # Generate model card
        card = _generate_model_card(config, output)
        if output.format == QuantFormat.EXL3:
            card_path = Path(output.output_path) / "README.md"
        else:
            card_path = Path(output.output_path).parent / f"README-{output.variant}.md"

        with open(card_path, "w") as f:
            f.write(card)


def _generate_model_card(config: QuantConfig, output: QuantOutput) -> str:
    """Generate README.md content matching existing huggingface.js format."""
    model_name = config.model_id.split("/")[-1]
    if config.hf_org:
        repo_id = f"{config.hf_org}/{model_name}-{output.variant}"
    else:
        repo_id = f"{model_name}-{output.variant}"

    # Quality metrics block
    quality_block = ""
    if output.quality:
        kl = output.quality.get("kl_div")
        ppl = output.quality.get("ppl")
        if kl is not None:
            quality_block += f"| KL divergence | {kl:.8f} |\n"
        if ppl is not None:
            quality_block += f"| Perplexity | {ppl:.6f} |\n"

    if output.format == QuantFormat.EXL3:
        return f"""---
base_model: {config.model_id}
library_name: exllamav3
tags:
- exl3
- exllamav3
- quantized
- text-generation
- blockquant
quantization_format: exl3
bits_per_weight: {output.variant}
---

# {model_name} — {output.variant}bpw EXL3

Auto-generated by [BlockQuant](https://github.com/Honkware/blockquant).

## Details

| Attribute | Value |
|-----------|-------|
| Base model | `{config.model_id}` |
| Format | EXL3 |
| BPW | {output.variant} |
| Head bits | {config.head_bits} |
| File size | {output.file_size_mb:.1f} MB |
{quality_block}
## Reproduce

```bash
bq-pipeline --model {config.model_id} --format exl3 --variants {output.variant}
```
"""
    else:
        return f"""---
tags:
- gguf
- quantized
- llama.cpp
- blockquant
---

# {model_name} — {output.variant.upper()} GGUF

Auto-generated by [BlockQuant](https://github.com/Honkware/blockquant).

## Details

| Attribute | Value |
|-----------|-------|
| Base model | `{config.model_id}` |
| Format | GGUF |
| Variant | {output.variant} |
| File size | {output.file_size_mb:.1f} MB |

## Reproduce

```bash
bq-pipeline --model {config.model_id} --format gguf --variants {output.variant}
```
"""
