broker_url = "redis://localhost:6379/0"
result_backend = "redis://localhost:6379/0"
task_serializer = "json"
result_serializer = "json"
accept_content = ["json"]
task_track_started = True
task_time_limit = 3600 * 6  # 6 hours for 70B models
task_soft_time_limit = 3600 * 5
task_acks_late = True
